/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.saintandreas.vr.vlc;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_chat=0x7f020000;
        public static final int ic_disk=0x7f020001;
        public static final int ic_error=0x7f020002;
        public static final int ic_eye=0x7f020003;
        public static final int ic_fire=0x7f020004;
        public static final int ic_folder=0x7f020005;
        public static final int ic_gear=0x7f020006;
        public static final int ic_gears=0x7f020007;
        public static final int ic_globe=0x7f020008;
        public static final int ic_headphones=0x7f020009;
        public static final int ic_heart=0x7f02000a;
        public static final int ic_home=0x7f02000b;
        public static final int ic_hourglass=0x7f02000c;
        public static final int ic_like=0x7f02000d;
        public static final int ic_login=0x7f02000e;
        public static final int ic_media_backward=0x7f02000f;
        public static final int ic_media_eject=0x7f020010;
        public static final int ic_media_fast_forward=0x7f020011;
        public static final int ic_media_fast_rewind=0x7f020012;
        public static final int ic_media_forward=0x7f020013;
        public static final int ic_media_next=0x7f020014;
        public static final int ic_media_pause=0x7f020015;
        public static final int ic_media_play=0x7f020016;
        public static final int ic_media_plus=0x7f020017;
        public static final int ic_ok=0x7f020018;
        public static final int ic_plus=0x7f020019;
        public static final int ic_print=0x7f02001a;
        public static final int ic_redo=0x7f02001b;
        public static final int ic_star=0x7f02001c;
        public static final int ic_sync=0x7f02001d;
        public static final int ic_text_document=0x7f02001e;
        public static final int ic_video=0x7f02001f;
        public static final int ic_volume_mute=0x7f020020;
    }
    public static final class id {
        public static final int help=0x7f050001;
        public static final int new_game=0x7f050000;
    }
    public static final class menu {
        public static final int test=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f030000;
        public static final int help=0x7f030002;
        public static final int new_game=0x7f030001;
    }
}
